/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadosweb.Telas;


/**
 *
 * @author andre
 */
public class Bet extends javax.swing.JFrame {

    /**
     * Creates new form Bet
     */
    public Bet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        TConfrontos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TConfrontos.setBackground(new java.awt.Color(0, 0, 0));
        TConfrontos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TConfrontos.setForeground(new java.awt.Color(255, 255, 255));
        TConfrontos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TConfrontos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TConfrontos.setSelectionBackground(new java.awt.Color(51, 51, 51));
        TConfrontos.setShowVerticalLines(false);
        TConfrontos.getTableHeader().setReorderingAllowed(false);
        TConfrontos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TConfrontosMouseClicked(evt);
            }
        });
        TConfrontos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TConfrontosPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(TConfrontos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TConfrontosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TConfrontosMouseClicked
        // TODO add your handling code here:

        Analise a = new Analise();
        int progresso = 0;

        /*new Thread() {
           public void run() {
                if (TableConfrontos.getSelectedColumn() == 3) {
                    ProgressBar.setValue(10);
                    Labelprogresso.setText("Criando tabelas...");
                    a.lastGames(TableConfrontos.getValueAt(TableConfrontos.getSelectedRow(), 3).toString());

                    ProgressBar.setValue(35);
                    Labelprogresso.setText("Extraindo dados");

                    try {
                        ArrayList dados = new ArrayList();
                        dados = a.desempenho(TableConfrontos.getValueAt(TableConfrontos.getSelectedRow(), 3).toString());

                        Document doc;
                        doc = Jsoup.connect(TableConfrontos.getValueAt(TableConfrontos.getSelectedRow(), 3).toString()).get();
                        Elements stats = doc.getElementsByClass("stats-game-head-teamname hide-mobile");

                        URL casa = new URL(stats.get(0).select("a").select("img").attr("src"));
                        Image imagem = ImageIO.read(casa);

                        URL fora = new URL(stats.get(1).select("a").select("img").attr("src"));
                        Image imagem1 = ImageIO.read(fora);

                        ImageIcon icon = new ImageIcon(imagem);
                        ImageIcon icon2 = new ImageIcon(imagem1);
                        icon.setImage(icon.getImage().getScaledInstance(30, 30, 100));
                        icon2.setImage(icon2.getImage().getScaledInstance(30, 30, 100));

                        lteste.setIcon(icon);
                        lteste1.setIcon(icon2);

                        DefaultTableModel analises = (DefaultTableModel) TableAnalises.getModel();
                        DefaultTableModel confrontos = (DefaultTableModel) TableConfrontos.getModel();
                        if (!dados.get(2).equals("")) {
                            Object[] inserir = {icon, dados.get(0) + " x " + dados.get(1) + "   " + dados.get(2) + " | " + dados.get(3),
                                icon2, TableConfrontos.getValueAt(TableConfrontos.getSelectedRow(), 3).toString()};
                            analises.addRow(inserir);
                            confrontos.removeRow(TableConfrontos.getSelectedRow());
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Análise não disponivel");
                        ProgressBar.setValue(0);
                        Labelprogresso.setText("Erro na analise");
                        DefaultTableModel erro = (DefaultTableModel) TableConfrontos.getModel();
                        erro.removeRow(TableConfrontos.getSelectedRow());

                    }

                    a.show();
                    a.setSize(760, 600);
                    a.setLocation(300, 10);

                    ProgressBar.setValue(100);
                    Labelprogresso.setText("Concluido");

                }
            }
        }.start();*/
    }//GEN-LAST:event_TConfrontosMouseClicked

    private void TConfrontosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TConfrontosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TConfrontosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TConfrontos;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
