/* * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadosweb.Telas;

import BancoDados.DAO;
import BancoDados.ObterDados;
import java.awt.Color;
import java.awt.Image;
import java.awt.PopupMenu;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.text.TableView;
import javax.swing.text.TableView.TableCell;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author andre
 */
public class DadosResult extends javax.swing.JFrame {

    /**
     * Creates new form DadosResult
     */
    public DadosResult() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jBFiltrar = new javax.swing.JButton();
        jCBResult = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResultadosJogos = new javax.swing.JTable();
        jCano = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CampanhaCasa = new javax.swing.JPanel();
        jLinf = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMercados = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablecamp = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablecamp1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFdata = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Competicao", "Jogos", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResultados.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableResultadosComponentAdded(evt);
            }
        });
        jTableResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableResultadosMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableResultados);
        if (jTableResultados.getColumnModel().getColumnCount() > 0) {
            jTableResultados.getColumnModel().getColumn(0).setResizable(false);
            jTableResultados.getColumnModel().getColumn(0).setHeaderValue("Competicao");
            jTableResultados.getColumnModel().getColumn(1).setResizable(false);
            jTableResultados.getColumnModel().getColumn(2).setResizable(false);
        }

        jBFiltrar.setText("Filtrar");
        jBFiltrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBFiltrarMouseClicked(evt);
            }
        });
        jBFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFiltrarActionPerformed(evt);
            }
        });

        jCBResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Green", "Red" }));

        jTableResultadosJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Confronto", "Placar", "Prognostico", "Estatisticas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResultadosJogos.setColumnSelectionAllowed(true);
        jTableResultadosJogos.getTableHeader().setReorderingAllowed(false);
        jTableResultadosJogos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableResultadosJogosComponentAdded(evt);
            }
        });
        jTableResultadosJogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultadosJogosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableResultadosJogosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableResultadosJogos);
        jTableResultadosJogos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableResultadosJogos.getColumnModel().getColumnCount() > 0) {
            jTableResultadosJogos.getColumnModel().getColumn(0).setResizable(false);
            jTableResultadosJogos.getColumnModel().getColumn(1).setResizable(false);
            jTableResultadosJogos.getColumnModel().getColumn(2).setResizable(false);
            jTableResultadosJogos.getColumnModel().getColumn(4).setResizable(false);
        }

        jCano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020" }));
        jCano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCanoItemStateChanged(evt);
            }
        });
        jCano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCanoFocusLost(evt);
            }
        });
        jCano.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jCanoMouseWheelMoved(evt);
            }
        });
        jCano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCanoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCanoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCanoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCanoMouseReleased(evt);
            }
        });
        jCano.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jCanoComponentShown(evt);
            }
        });
        jCano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCanoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Temporada");

        CampanhaCasa.setBackground(new java.awt.Color(153, 153, 153));
        CampanhaCasa.setLayout(new java.awt.BorderLayout());

        jTableMercados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Competicao", "Jogos", "Greens(%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMercados.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableMercadosComponentAdded(evt);
            }
        });
        jTableMercados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMercadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableMercadosMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTableMercados);
        if (jTableMercados.getColumnModel().getColumnCount() > 0) {
            jTableMercados.getColumnModel().getColumn(0).setResizable(false);
            jTableMercados.getColumnModel().getColumn(1).setResizable(false);
            jTableMercados.getColumnModel().getColumn(2).setResizable(false);
            jTableMercados.getColumnModel().getColumn(2).setHeaderValue("Greens(%)");
        }

        jTablecamp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Clube", "Aproveitamento", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablecamp.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTablecampComponentAdded(evt);
            }
        });
        jTablecamp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecampMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTablecampMouseEntered(evt);
            }
        });
        jScrollPane5.setViewportView(jTablecamp);
        if (jTablecamp.getColumnModel().getColumnCount() > 0) {
            jTablecamp.getColumnModel().getColumn(0).setResizable(false);
            jTablecamp.getColumnModel().getColumn(1).setResizable(false);
            jTablecamp.getColumnModel().getColumn(2).setResizable(false);
            jTablecamp.getColumnModel().getColumn(3).setResizable(false);
            jTablecamp.getColumnModel().getColumn(3).setHeaderValue("null");
        }

        jTablecamp1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Clube", "Comp", "Greens(%)", "Jogos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablecamp1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTablecamp1ComponentAdded(evt);
            }
        });
        jTablecamp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecamp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTablecamp1MouseEntered(evt);
            }
        });
        jScrollPane6.setViewportView(jTablecamp1);
        if (jTablecamp1.getColumnModel().getColumnCount() > 0) {
            jTablecamp1.getColumnModel().getColumn(0).setResizable(false);
            jTablecamp1.getColumnModel().getColumn(1).setResizable(false);
            jTablecamp1.getColumnModel().getColumn(2).setResizable(false);
            jTablecamp1.getColumnModel().getColumn(3).setResizable(false);
            jTablecamp1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Melhores Clubes");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Melhores Prognosticos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Confrontos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Campanha da competição");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mercados");

        try {
            jFdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setText("ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jCBResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBFiltrar)
                .addGap(321, 321, 321)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLinf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CampanhaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jCano, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jFdata, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCBResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBFiltrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLinf)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampanhaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(jLabel2)))
                                .addGap(10, 10, 10)
                                .addComponent(jCano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jFdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1))
                                        .addGap(2, 2, 2)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableResultadosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableResultadosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableResultadosComponentAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here

        jTableResultados.getColumnModel().getColumn(0).setMaxWidth(200);
        jTableResultados.getColumnModel().getColumn(0).setMinWidth(200);
        jTableResultados.getColumnModel().getColumn(1).setMaxWidth(50);
        jTableResultados.getColumnModel().getColumn(1).setMinWidth(50);
        jTableResultados.getColumnModel().getColumn(2).setMaxWidth(50);
        jTableResultados.getColumnModel().getColumn(2).setMinWidth(50);

        jTableResultadosJogos.getColumnModel().getColumn(0).setMaxWidth(50);
        jTableResultadosJogos.getColumnModel().getColumn(0).setMinWidth(50);
        jTableResultadosJogos.getColumnModel().getColumn(1).setMaxWidth(150);
        jTableResultadosJogos.getColumnModel().getColumn(1).setMinWidth(150);
        jTableResultadosJogos.getColumnModel().getColumn(2).setMaxWidth(50);
        jTableResultadosJogos.getColumnModel().getColumn(2).setMinWidth(50);

        jTablecamp.getColumnModel().getColumn(0).setMinWidth(30);
        jTablecamp.getColumnModel().getColumn(0).setMaxWidth(30);
        jTablecamp.getColumnModel().getColumn(1).setMaxWidth(150);
        jTablecamp.getColumnModel().getColumn(1).setMinWidth(150);
        jTablecamp.getColumnModel().getColumn(2).setMaxWidth(50);
        jTablecamp.getColumnModel().getColumn(2).setMinWidth(50);
        jTablecamp.getColumnModel().getColumn(3).setMaxWidth(1);
        jTablecamp.getColumnModel().getColumn(3).setMinWidth(1);
        jTablecamp.setRowHeight(20);

        TableColumnModel columnModel = jTablecamp.getColumnModel();
        JTableRendererImageCell renderer = new JTableRendererImageCell();

        columnModel.getColumn(0).setCellRenderer(renderer);

        jTablecamp1.getColumnModel().getColumn(0).setMinWidth(50);
        jTablecamp1.getColumnModel().getColumn(0).setMaxWidth(50);
        jTablecamp1.getColumnModel().getColumn(1).setMaxWidth(80);
        jTablecamp1.getColumnModel().getColumn(1).setMinWidth(80);
        jTablecamp1.getColumnModel().getColumn(2).setMaxWidth(80);
        jTablecamp1.getColumnModel().getColumn(2).setMinWidth(80);
        jTablecamp1.getColumnModel().getColumn(3).setMaxWidth(50);
        jTablecamp1.getColumnModel().getColumn(3).setMinWidth(50);
        jTablecamp1.getColumnModel().getColumn(4).setMaxWidth(50);
        jTablecamp1.getColumnModel().getColumn(4).setMinWidth(50);
        jTablecamp1.setRowHeight(30);
        TableColumnModel columnModel1 = jTablecamp1.getColumnModel();
        JTableRendererImageCell renderer1 = new JTableRendererImageCell();
        DefaultTableModel bestCamp = (DefaultTableModel) jTablecamp1.getModel();
        columnModel1.getColumn(0).setCellRenderer(renderer1);

        jTableResultados.setRowHeight(20);
        jTableResultadosJogos.setRowHeight(20);
        JTableUtilities.setCellsAlignment(jTableResultados, SwingConstants.CENTER, 1);
        JTableUtilities.setCellsAlignment(jTableResultados, SwingConstants.CENTER, 2);

        String sql = "select timecasa as competicao, (greencasa+greenfora)*100/(jcasa+jfora) as \"greens\",c1 as link,jcasa+jfora as jogos from\n"
                + "		(((Select timecasa as tc,count(timecasa) as Jcasa,competicao as c from prognosticos\n"
                + "				group by timecasa order by timecasa)a\n"
                + "		\n"
                + "        join\n"
                + "		\n"
                + "        (select timecasa,count(timecasa) as greenCasa,competicao as c1  from prognosticos	\n"
                + "			where result=\"green\"\n"
                + "				group by timecasa order by timecasa)b\n"
                + "			on  timecasa=tc)\n"
                + "		\n"
                + "        join\n"
                + "		\n"
                + "        (select timefora,count(timecasa) as greenfora,competicao as c2  from prognosticos	\n"
                + "			where result=\"green\"\n"
                + "				group by timefora order by timefora)c    \n"
                + "		on timecasa=timefora)\n"
                + "        \n"
                + "        join\n"
                + "		\n"
                + "		(select timefora as y,count(timeFora) as Jfora,competicao as c3  from prognosticos	\n"
                + "		group by y order by y)d\n"
                + "		on timecasa=y\n"
                + "	\n"
                + "    order by greens desc\n"
                + "        ";

        Funcoes f = new Funcoes();

        try {

            ObterDados o = new ObterDados();

            for (DAO a : o.ConsultaJoin(sql)) {
                Object[] inserir = {f.buscarImagem(a.getLink(), a.getCompeticao(), 25, 25),
                     a.getCompeticao(), a.getLink(), a.getGreen() + "%", a.getTjogos()};
                bestCamp.addRow(inserir);
            }

        } catch (IOException | SQLException ex) {
            Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formWindowOpened

    private void jBFiltrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBFiltrarMouseClicked

        DefaultTableModel listaRES = (DefaultTableModel) jTableResultados.getModel();
        DefaultTableModel camp = (DefaultTableModel) jTablecamp1.getModel();

        int linhas = jTablecamp1.getRowCount();
        Funcoes f = new Funcoes();

        for (int i = 0; i < linhas; i++) {
            camp.removeRow(0);
        }

        jTablecamp1 = f.Resultadosgerais(jTablecamp1);

        try {

            String sql = "select lk as link,c as competicao,tc as greens,tc2 as jogos from \n"
                    + "(select 1 as x, link as lk,competicao c2,count(timeCasa) tc from prognosticos\n"
                    + "    where result=\"" + jCBResult.getSelectedItem().toString() + "\"\n"
                    + "    group by c2) a\n"
                    + "join\n"
                    + "(select 2 as x, link as lk2,competicao c,count(timeCasa) tc2 from prognosticos\n"
                    + "    group by c) b\n"
                    + "    on c=c2;";

            ObterDados obt = new ObterDados();

            while (jTableResultados.getModel().getRowCount() > 0) {
                ((DefaultTableModel) jTableResultados.getModel()).removeRow(0);
            }

            for (DAO a : obt.ConsultaJoin(sql)) {

                Object[] resul = {a.getCompeticao(), a.getTjogos(),
                    a.getGreen() * 100 / a.getTjogos()};
                listaRES.addRow(resul);

            }

        } catch (IOException | SQLException ex) {
            Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBFiltrarMouseClicked

    private void jTableResultadosJogosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableResultadosJogosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableResultadosJogosComponentAdded


    private void jTableResultadosJogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultadosJogosMouseClicked

        String[] logoComp = jTableResultadosJogos.getValueAt(jTableResultadosJogos.getSelectedRow(), 4).toString().split(",");
        Funcoes f = new Funcoes();
        if (jTableResultadosJogos.getSelectedColumn() == 4) {
            try {
                f.abrirLink(logoComp[0].replace("live", "odds#tab=odds_graph_1"));
            } catch (IOException | URISyntaxException ex) {
                Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (jTableResultadosJogos.getSelectedColumn() == 1) {
            try {
                f.analisarJogo(logoComp[0].replace("live", ""));
                jLinf.setText("carregando analise de "
                        + jTableResultadosJogos.getValueAt(jTableResultadosJogos.getSelectedRow(), 1).toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erro ao carregar analise\n" + e);
            }
        }

        jLinf.setText("");

        /*
        
        
        
        URL comp;
        URL comp1;
        try {
            comp = new URL(logoComp[1]);
            Image imagem = ImageIO.read(comp);
            ImageIcon icon = new ImageIcon(imagem);
            icon.setImage(icon.getImage().getScaledInstance(jLabelLogoC.getWidth(), jLabelLogoC.getHeight(), 1));
            jLabelLogoC.setIcon(icon);

            comp1 = new URL(logoComp[2]);
            Image imagem1 = ImageIO.read(comp1);
            ImageIcon icon1 = new ImageIcon(imagem1);
            icon1.setImage(icon1.getImage().getScaledInstance(jLabelLogoF.getWidth(), jLabelLogoF.getHeight(), 1));
            jLabelLogoF.setIcon(icon1);

        } catch (MalformedURLException ex) {
            Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
        }
       
         */

    }//GEN-LAST:event_jTableResultadosJogosMouseClicked

    private void jTableResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultadosMouseClicked
        DefaultTableModel listaRES = (DefaultTableModel) jTableResultadosJogos.getModel();
        DefaultTableModel listaMER = (DefaultTableModel) jTableMercados.getModel();
        DefaultTableModel listaCAMP = (DefaultTableModel) jTablecamp.getModel();
        ObterDados obt;
        ObterDados data;
        ObterDados mercados;
        ObterDados camp;

        String sql = "select *from prognosticos where competicao=\""
                + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\" and result = \""
                + jCBResult.getSelectedItem() + "\";";

        try {

            while (jTableResultadosJogos.getModel().getRowCount() > 0) {
                ((DefaultTableModel) jTableResultadosJogos.getModel()).removeRow(0);
            }

            obt = new ObterDados();

            for (DAO a : obt.ProgSalvo(sql)) {

                Object[] inserir = {a.getData().substring(0, 5),
                    a.getTimeCasa() + " x " + a.getTimeFora(), a.getPlacar(),
                    a.getProg(), a.getLink().replace("prelive", "live") + "," + a.getLogo()};

                listaRES.addRow(inserir);

            }

        } catch (IOException ex) {
            Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            jCano.removeAllItems();

            sql = "SELECT idPrognosticos,competicao,timeCasa,"
                    + "timeFora,prog,placar,result,link,logoTimes,year(data) as 'data' from prognosticos\n"
                    + "where competicao = \"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\" group by year(data) order by  data desc ;";

            data = new ObterDados();

            for (DAO a : data.ProgSalvo(sql)) {
                jCano.addItem(a.getData());
            }

        } catch (IOException e) {
        }

        //inserir dados dos mercados
        try {

            sql = "select lk as link,mercado1 as competicao,totmer as greens,vit*100/totmer as jogos from\n"
                    + " ((select 1 as x,link as lk, right(prog,7) as mercado1,count(result) as totmer from prognosticos where "
                    + "competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\"\n"
                    + "	group by mercado1 order by mercado1) a    \n"
                    + "		join\n"
                    + " (select 2 as x, link as lk2,right(prog,7) as mercado2,count(result) as vit from prognosticos where "
                    + "competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\" and result=\"green\"\n"
                    + "	group by mercado2 order by mercado2) b\n"
                    + "		on mercado1=mercado2)\n"
                    + "		join\n"
                    + " (select 3 as x, link as lk3,right(prog,7) as mercado3,count(result) as der from prognosticos where "
                    + "competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\" and result=\"red\"\n"
                    + "	group by mercado3 order by mercado3) c\n"
                    + "		on mercado2=mercado3";

            while (jTableMercados.getModel().getRowCount() > 0) {
                ((DefaultTableModel) jTableMercados.getModel()).removeRow(0);
            }

            mercados = new ObterDados();

            for (DAO b : mercados.ConsultaJoin(sql)) {

                Object[] addMER = {b.getCompeticao().replaceAll("-", "").replace("ver", "Over").replace("der", "U"
                    + "nder"), b.getGreen(), b.getTjogos()};
                listaMER.addRow(addMER);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro nos mercados\n" + e);
        }

        try {

            //inserir dados na campanha
            sql = "select timecasa as competicao, (greencasa+greenfora)*100/(jcasa+jfora) as \"greens\",\"link\""
                    + ",(greencasa+greenfora)*100/(jcasa+jfora) as jogos from\n"
                    + "		(((Select timecasa as tc,count(timecasa) as Jcasa from prognosticos\n"
                    + "			where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\"\n"
                    + "				group by timecasa order by timecasa)a\n"
                    + "		\n"
                    + "        join\n"
                    + "		\n"
                    + "        (select timecasa,count(timecasa) as greenCasa  from prognosticos	\n"
                    + "			where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\" and result=\"green\"\n"
                    + "				group by timecasa order by timecasa)b\n"
                    + "			on  timecasa=tc)\n"
                    + "		\n"
                    + "        join\n"
                    + "		\n"
                    + "        (select timefora,count(timecasa) as greenfora  from prognosticos	\n"
                    + "			where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\" and result=\"green\"\n"
                    + "				group by timefora order by timefora)c    \n"
                    + "		on timecasa=timefora)\n"
                    + "        \n"
                    + "        join\n"
                    + "		\n"
                    + "		(select timefora as y,count(timeFora) as Jfora  from prognosticos	\n"
                    + "	where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\" \n"
                    + "		group by y order by y)d\n"
                    + "		on timecasa=y\n"
                    + "	\n"
                    + "    order by greens desc";

            while (jTablecamp.getModel().getRowCount() > 0) {
                ((DefaultTableModel) jTablecamp.getModel()).removeRow(0);
            }

            camp = new ObterDados();

            Funcoes f = new Funcoes();
            for (DAO c : camp.ConsultaJoin(sql)) {
                Object[] addCamp = {
                    f.buscarImagem(jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0).toString(),
                    c.getCompeticao(), 20, 20), c.getCompeticao(), c.getGreen(), c.getLink()};
                listaCAMP.addRow(addCamp);
            }

        } catch (IOException | SQLException e) {
        }


    }//GEN-LAST:event_jTableResultadosMouseClicked

    private void jTableResultadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultadosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableResultadosMouseEntered

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked


    }//GEN-LAST:event_formMouseClicked

    private void jCanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCanoActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:

    }//GEN-LAST:event_jCanoActionPerformed

    private void jCanoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCanoMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jCanoMousePressed

    private void jCanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCanoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jCanoMouseClicked

    private void jCanoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCanoItemStateChanged
        // TODO add your handling code here:

        grafico();
    }//GEN-LAST:event_jCanoItemStateChanged

    private void jCanoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jCanoMouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jCanoMouseWheelMoved

    private void jCanoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCanoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jCanoFocusLost

    private void jCanoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jCanoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jCanoComponentShown

    private void jCanoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCanoMouseReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_jCanoMouseReleased

    private void jCanoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCanoMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_jCanoMouseEntered

    private void jTableResultadosJogosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultadosJogosMousePressed
        // TODO add your handling code here:

        String[] logoComp = jTableResultadosJogos.getValueAt(jTableResultadosJogos.getSelectedRow(), 4).toString().split(",");

        Funcoes f = new Funcoes();
        f.analisarJogo(logoComp[0]);


    }//GEN-LAST:event_jTableResultadosJogosMousePressed

    private void jTableMercadosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableMercadosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMercadosComponentAdded

    private void jTableMercadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMercadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMercadosMouseClicked

    private void jTableMercadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMercadosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMercadosMouseEntered

    private void jTablecampComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTablecampComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablecampComponentAdded

    private void jTablecampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecampMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablecampMouseClicked

    private void jTablecampMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecampMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablecampMouseEntered

    private void jTablecamp1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTablecamp1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablecamp1ComponentAdded

    private void jTablecamp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecamp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablecamp1MouseClicked

    private void jTablecamp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecamp1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablecamp1MouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        String sql;
        ObterDados mercados;
        ObterDados camp;
        try {

            sql = "select lk as link,mercado1 as competicao,totmer as greens,vit*100/totmer as jogos from\n"
                    + " ((select 1 as x,link as lk, right(prog,7) as mercado1,count(result) as totmer from prognosticos where "
                    + "competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\" and data > \"" + jFdata.getText() + "\" \n"
                    + "	group by mercado1 order by mercado1) a    \n"
                    + "		join\n"
                    + " (select 2 as x, link as lk2,right(prog,7) as mercado2,count(result) as vit from prognosticos where "
                    + "competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\" and result=\"green\" and data > \"" + jFdata.getText() + "\"\n"
                    + "	group by mercado2 order by mercado2) b\n"
                    + "		on mercado1=mercado2)\n"
                    + "		join\n"
                    + " (select 3 as x, link as lk3,right(prog,7) as mercado3,count(result) as der from prognosticos where "
                    + "competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\" and result=\"red\" and data > \"" + jFdata.getText() + "\"\n"
                    + "	group by mercado3 order by mercado3) c\n"
                    + "		on mercado2=mercado3";

            while (jTableMercados.getModel().getRowCount() > 0) {
                ((DefaultTableModel) jTableMercados.getModel()).removeRow(0);
            }

            DefaultTableModel listaMER = (DefaultTableModel) jTableMercados.getModel();
            mercados = new ObterDados();
            for (DAO b : mercados.ConsultaJoin(sql)) {

                Object[] addMER = {b.getCompeticao().replaceAll("-", "").replace("ver", "Over").replace("der", "U"
                    + "nder"), b.getGreen(), b.getTjogos()};
                listaMER.addRow(addMER);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "erro nos mercados\n" + e);
        } catch (IOException ex) {
            Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            sql = "select timecasa as competicao, (greencasa+greenfora)*100/(jcasa+jfora) as \"greens\",\"link\""
                    + ",(greencasa+greenfora)*100/(jcasa+jfora) as jogos from\n"
                    + "		(((Select timecasa as tc,count(timecasa) as Jcasa from prognosticos\n"
                    + "			where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\""
                    + "and data > \"" + jFdata.getText() + "\"\n"
                    + "				group by timecasa order by timecasa)a\n"
                    + "		\n"
                    + "        join\n"
                    + "		\n"
                    + "        (select timecasa,count(timecasa) as greenCasa  from prognosticos	\n"
                    + "			where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\" and result=\"green\""
                    + "and data > \"" + jFdata.getText() + "\"\n"
                    + "				group by timecasa order by timecasa)b\n"
                    + "			on  timecasa=tc)\n"
                    + "		\n"
                    + "        join\n"
                    + "		\n"
                    + "        (select timefora,count(timecasa) as greenfora  from prognosticos	\n"
                    + "			where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\" and result=\"green\""
                    + "and data > \"" + jFdata.getText() + "\"\n"
                    + "				group by timefora order by timefora)c    \n"
                    + "		on timecasa=timefora)\n"
                    + "        \n"
                    + "        join\n"
                    + "		\n"
                    + "		(select timefora as y,count(timeFora) as Jfora  from prognosticos	\n"
                    + "	where competicao=\"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0) + "\" "
                    + "and data > \"" + jFdata.getText() + "\"\n"
                    + "		group by y order by y)d\n"
                    + "		on timecasa=y\n"
                    + "	\n"
                    + "    order by greens desc";

            while (jTablecamp.getModel().getRowCount() > 0) {
                ((DefaultTableModel) jTablecamp.getModel()).removeRow(0);
            }
            camp = new ObterDados();
            DefaultTableModel listaCAMP = (DefaultTableModel) jTablecamp.getModel();
            Funcoes f = new Funcoes();
            for (DAO c : camp.ConsultaJoin(sql)) {
                Object[] addCamp = {
                    f.buscarImagem(jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0).toString(),
                    c.getCompeticao(), 20, 20), c.getCompeticao(), c.getGreen(), c.getLink()};
                listaCAMP.addRow(addCamp);
            }

        } catch (IOException | SQLException e) {
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void jBFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFiltrarActionPerformed

    private void grafico() {

        DefaultCategoryDataset campanha = new DefaultCategoryDataset();

        JFreeChart chart = ChartFactory.createLineChart("RESULTADOS", "MES", "JOGOS", campanha, PlotOrientation.VERTICAL, false, false, false);

        CategoryPlot catplot = chart.getCategoryPlot();

        //((BarRenderer)catplot.getRenderer()).setBarPainter(new StandardBarPainter());
        catplot.setRangeGridlinePaint(Color.WHITE);
        catplot.setBackgroundPaint(Color.BLACK);
        catplot.setDomainGridlinePaint(Color.WHITE);

        ChartPanel chartPanel = new ChartPanel(chart);

        CampanhaCasa.removeAll();
        CampanhaCasa.add(chartPanel);
        CampanhaCasa.validate();

        String sql = "select mes as idPrognosticos,totRes as competicao,totJog as timeCasa,timeFora,prog,placar,result,link,logoTimes,year(data) as 'data' from\n"
                + "\n"
                + "(select month(data) as mes,count(result) as totRes,timeCasa,timeFora,prog,\n"
                + "	placar,result,link,logoTimes,data  from prognosticos\n"
                + "		where result = \"red\" AND COMPETICAO = \"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                + "\" \n"
                + "        AND YEAR(DATA) = \"" + jCano.getSelectedItem() + "\"   group by month(data) order by month(data) asc) a\n"
                + "\n"
                + "join\n"
                + "\n"
                + "(select  month(data) as mes1, count(result) as totJog,timeCasa as tc,timeFora as tf,prog as pg,\n"
                + "			placar as pl,result as rs,link as lk,logoTimes as lt,data as dt  from prognosticos\n"
                + "			where COMPETICAO = \"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                + "\"  and year(data)=\"" + jCano.getSelectedItem() + "\" and placar<>\"\"\n"
                + "            group by month(data)) b\n"
                + "		\n"
                + "        on mes=mes1;";

        /*"select month(data) as idPrognosticos,count(result) as competicao,timeCasa,timeFora,prog,\n" +
"	placar,result,link,logoTimes,data  from prognosticos\n" +
"		where result = \"red\" AND COMPETICAO = \""+jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                +"\" AND YEAR(DATA) = \""+jCano.getSelectedItem().toString()
                +"\" group by month(data) order by month(data) asc";
         */
        try {
            ObterDados obt = new ObterDados();
            int tot = 0, par = 0;
            for (DAO a : obt.ProgSalvo(sql)) {
                tot = Integer.parseInt(a.getTimeCasa());
                par = Integer.parseInt(a.getCompeticao());
                campanha.setValue(par * 100 / tot, "RED", a.getIdPrognostico() + "(" + tot + " jogos)");
                // System.out.println(tot + " " + par);
            }

            sql = "select mes as idPrognosticos,totRes as competicao,totJog as timeCasa,timeFora,prog,placar,result,link,logoTimes,year(data) as 'data' from\n"
                    + "\n"
                    + "(select month(data) as mes,count(result) as totRes,timeCasa,timeFora,prog,\n"
                    + "	placar,result,link,logoTimes,data  from prognosticos\n"
                    + "		where result = \"green\" AND COMPETICAO = \"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\" \n"
                    + "        AND YEAR(DATA) = \"" + jCano.getSelectedItem() + "\"   group by month(data) order by month(data) asc) a\n"
                    + "\n"
                    + "join\n"
                    + "\n"
                    + "(select  month(data) as mes1, count(result) as totJog,timeCasa as tc,timeFora as tf,prog as pg,\n"
                    + "			placar as pl,result as rs,link as lk,logoTimes as lt,data as dt  from prognosticos\n"
                    + "			where COMPETICAO = \"" + jTableResultados.getValueAt(jTableResultados.getSelectedRow(), 0)
                    + "\"  and year(data)=\"" + jCano.getSelectedItem() + "\" and placar<>\"\"\n"
                    + "            group by month(data)) b\n"
                    + "		\n"
                    + "        on mes=mes1;";

            for (DAO a : obt.ProgSalvo(sql)) {

                tot = Integer.parseInt(a.getTimeCasa());
                par = Integer.parseInt(a.getCompeticao());
                campanha.setValue(par * 100 / tot, "GREEN", a.getIdPrognostico() + "(" + tot + " jogos)");
                // System.out.println(tot + " " + par);
            }

        } catch (IOException ex) {
            Logger.getLogger(DadosResult.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CampanhaCasa;
    private javax.swing.JButton jBFiltrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBResult;
    private javax.swing.JComboBox<String> jCano;
    private javax.swing.JFormattedTextField jFdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLinf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableMercados;
    private javax.swing.JTable jTableResultados;
    private javax.swing.JTable jTableResultadosJogos;
    private javax.swing.JTable jTablecamp;
    private javax.swing.JTable jTablecamp1;
    // End of variables declaration//GEN-END:variables
}
