/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadosweb.Telas;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jsoup.Jsoup;             
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author andre
 */
public class selecComp extends javax.swing.JDialog {

    /**
     * Creates new form selecComp
     */
    public selecComp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    String nomeComp = "";

    public String getNomeComp() {
        return nomeComp;
    }

    public void setNomeComp(String nomeComp) {
        this.nomeComp = nomeComp;
    }

    ArrayList<Object[]> linhas = new ArrayList<>();

    public ArrayList<Object[]> getLinhas() {
        return linhas;
    }

    public void setLinhas(ArrayList<Object[]> linhas) {
        this.linhas = linhas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBInserir = new javax.swing.JButton();
        jLjogosComp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCCamp = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCRfinal = new javax.swing.JComboBox<>();
        jLabelLink = new javax.swing.JLabel();
        jCRodadas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablejogos = new javax.swing.JTable();
        jBAtualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jCPaises = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBInserir.setText("inserir");
        jBInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBInserirMouseClicked(evt);
            }
        });

        jLjogosComp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLjogosComp.setText("0%");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("País");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Campeonato");

        jCCamp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCampActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Rodadas");

        jCRfinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCRfinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCRfinalMouseClicked(evt);
            }
        });
        jCRfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRfinalActionPerformed(evt);
            }
        });

        jLabelLink.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabelLink.setText("link");

        jCRodadas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("a");

        jTablejogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data do Evento", "Confronto", "Placar", "Estatisticas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablejogos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTablejogosComponentAdded(evt);
            }
        });
        jTablejogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablejogosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablejogos);

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAtualizarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jogos");

        jCPaises.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCPaises.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCPaisesItemStateChanged(evt);
            }
        });
        jCPaises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCPaisesMouseClicked(evt);
            }
        });
        jCPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPaisesActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jCPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLink, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLjogosComp))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCRfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jCRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabelLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCCamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLjogosComp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCRfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jCRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jBAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jBInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInserirMouseClicked

        this.dispose();


    }//GEN-LAST:event_jBInserirMouseClicked

    public boolean ponNulo(String url) throws IOException {
        Document doc = Jsoup.connect(url).get();

        try {
            String qJogos = doc.getElementById("last-week").attr("value");

            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private void jCCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCampActionPerformed

        jCRodadas.removeAllItems();
        jCRfinal.removeAllItems();

        if (jCCamp.getItemCount() > 0) {

            DefaultTableModel Tjogos = (DefaultTableModel) jTablejogos.getModel();

            String[] link = jCCamp.getSelectedItem().toString().split("-");
            jLabelLink.setText(link[1].trim());

            while (Tjogos.getRowCount() > 0) {
                Tjogos.removeRow(0);
            }

            if (jLabelLink.getText().length() > 20) {

                try {
                    Document doc = Jsoup.connect(jLabelLink.getText()).get();

                    if (ponNulo(jLabelLink.getText())) {

                        for (int f = Integer.parseInt(doc.getElementById("last-week").attr("value")); f > 0; f--) {
                            jCRfinal.addItem(f + "");
                            jCRodadas.addItem((f) + "");
                        }
                    }

                    Elements jogos = doc.getElementsByClass("competition-rounds competition-half-padding").select("tr");

                    for (int i = 0; i < jogos.size(); i++) {
                        Object[] inserir = {jogos.get(i).select("td").get(1).text(),
                            jogos.get(i).select("td").get(2).text() + " x " + jogos.get(i).select("td").get(4).text(),
                            jogos.get(i).select("td").get(3).text(),
                            jogos.get(i).select("td").get(6).select("a").attr("href").replace("live", "prelive")};

                        Tjogos.addRow(inserir);
                    }

                    // Funcoes f = new Funcoes();
                    //Document doc = Jsoup.connect(url)
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Não pode conectar a:\n" + ex);
                }
            }
        }

    }//GEN-LAST:event_jCCampActionPerformed

    private void jCRfinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCRfinalMouseClicked

        jCRodadas.removeAllItems();
        int i = Integer.parseInt(jCRfinal.getSelectedItem().toString());
        int a = 1;
        while (a < i) {
            jCRodadas.addItem(a + "");
            a++;
        }
    }//GEN-LAST:event_jCRfinalMouseClicked

    private void jCRfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRfinalActionPerformed

    }//GEN-LAST:event_jCRfinalActionPerformed

    private void jTablejogosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTablejogosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablejogosComponentAdded

    private void jTablejogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablejogosMouseClicked

        if (jTablejogos.getSelectedColumn() == 7) {
            Funcoes f = new Funcoes();
            try {
                f.abrirLink(jTablejogos.getValueAt(jTablejogos.getSelectedRow(), 7).toString() + "/odds#tab=odds_graph_1");
            } catch (IOException | URISyntaxException ex) {
                JOptionPane.showMessageDialog(null, "Link invalido" + ex);
            }
        }
    }//GEN-LAST:event_jTablejogosMouseClicked

    private void jBAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtualizarMouseClicked

        new Thread() {
            public void run() {

                Funcoes f = new Funcoes();
                jTextArea.setText("Conectando...");

                DefaultTableModel Tjogos = (DefaultTableModel) jTablejogos.getModel();

                int r = Tjogos.getRowCount();
                while (r > 0) {
                    Tjogos.removeRow(r - 1);
                    r--;
                }

                int rTF = Integer.parseInt(jCRfinal.getSelectedItem().toString());
                int rT = Integer.parseInt(jCRodadas.getSelectedItem().toString());

                try {
                    Document doc2 = Jsoup.connect(jLabelLink.getText()).get();

                    while (rTF >= rT) {

                        String e = doc2.getElementsByClass("boxed basket").select("td").get(2).select("a").attr("href") + "/0/" + rTF;

                        System.out.println(e);

                        Document doc = Jsoup.connect(e).get();

                        Elements jogos = doc.getElementsByClass("competition-rounds competition-half-padding").select("tr");

                        for (int i = 0; i < jogos.size(); i++) {
                            Object[] inserir = {jogos.get(i).select("td").get(1).text(),
                                jogos.get(i).select("td").get(2).text() + " x " + jogos.get(i).select("td").get(4).text(),
                                jogos.get(i).select("td").get(3).text(),
                                jogos.get(i).select("td").get(6).select("a").attr("href")};

                            Object[] inserirLinhas = {jogos.get(i).select("td").get(2).text(), jogos.get(i).select("td").get(3).text(),
                                jogos.get(i).select("td").get(4).text(),
                                jogos.get(i).select("td").get(6).select("a").attr("href").replace("live", "prelive")
                            };

                            Tjogos.addRow(inserir);

                            linhas.add(inserirLinhas);

                        }
                        jTextArea.setText(jTextArea.getText() + "rodada " + rTF + "\n");
                        rTF--;
                    }

                } catch (IOException ex) {
                    jTextArea.setText(jTextArea.getText() + "erro na rodada " + rTF + "\n" + ex);
                    Logger.getLogger(Competicoes.class.getName()).log(Level.SEVERE, null, ex);
                }

                nomeComp = jCCamp.getSelectedItem().toString();

            }
        }.start();
    }//GEN-LAST:event_jBAtualizarMouseClicked

    private void jCPaisesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCPaisesItemStateChanged

    }//GEN-LAST:event_jCPaisesItemStateChanged

    private void jCPaisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCPaisesMouseClicked

    }//GEN-LAST:event_jCPaisesMouseClicked

    private void jCPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPaisesActionPerformed

        Funcoes f = new Funcoes();
        Document doc;
        try {
            doc = f.buscarArquivo(f.obterCaminho("../generate-football-tips/src/dadosweb/consultaComps.txt"));
            Elements comps = doc.getElementsByClass("boxed cpt-list").select("div").get(0)
                .getElementsByClass("toggle_content").get(jCPaises.getSelectedIndex()).select("a");

        jCCamp.removeAllItems();

        for (int i = 0; i < comps.size(); i++) {
            jCCamp.addItem(comps.get(i).attr("title") + "                                               "
                    + "                                                           -" + comps.get(i).attr("href"));
        }
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(selecComp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jCPaisesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        Funcoes f = new Funcoes();

        try {
            System.out.println();

            Document doc = f.buscarArquivo(f.obterCaminho("../generate-football-tips/src/dadosweb/consultaComps.txt"));

            Elements comps = doc.getElementsByClass("boxed cpt-list").select("div").get(0)
                    .getElementsByClass("toggle area");
            for (int i = 0; i < comps.size(); i++) {
                jCPaises.addItem(comps.get(i).text());
            }
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(selecComp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selecComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                selecComp dialog = new selecComp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBInserir;
    private javax.swing.JComboBox<String> jCCamp;
    private javax.swing.JComboBox<String> jCPaises;
    private javax.swing.JComboBox<String> jCRfinal;
    private javax.swing.JComboBox<String> jCRodadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelLink;
    private javax.swing.JLabel jLjogosComp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablejogos;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
