/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadosweb.Telas;

import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author andre
 */
public class Tabela extends javax.swing.JFrame {

    /**
     * Creates new form Tabela
     */
    public Tabela() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
  
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param url
     */
    
    
    
    
    
    public void GerarTabela(String url) throws IOException{
        
        
        
        // ## Gerar Tabela ## 
        Classificacao.getColumnModel().getColumn(0).setMaxWidth(30);
        Classificacao.getColumnModel().getColumn(0).setMinWidth(30);

        Classificacao.getColumnModel().getColumn(1).setMaxWidth(100);
        Classificacao.getColumnModel().getColumn(1).setMinWidth(100);

        Classificacao.getColumnModel().getColumn(2).setMaxWidth(30);
        Classificacao.getColumnModel().getColumn(2).setMinWidth(30);

        Classificacao.getColumnModel().getColumn(3).setMaxWidth(30);
        Classificacao.getColumnModel().getColumn(3).setMinWidth(30);

        Classificacao.getColumnModel().getColumn(4).setMaxWidth(30);
        Classificacao.getColumnModel().getColumn(4).setMinWidth(30);

        Classificacao.getColumnModel().getColumn(5).setMaxWidth(30);
        Classificacao.getColumnModel().getColumn(6).setMinWidth(30);

        Classificacao.getColumnModel().getColumn(6).setMaxWidth(30);
        Classificacao.getColumnModel().getColumn(6).setMinWidth(30);

        Classificacao.getColumnModel().getColumn(7).setMaxWidth(50);
        Classificacao.getColumnModel().getColumn(7).setMinWidth(50);

        
        DefaultTableModel model = (DefaultTableModel) Classificacao.getModel();

      /*
         String[] classifiacao = null;

        Document doc = Jsoup.connect("https://www.academiadasapostasbrasil.com/stats/"
                + "match/inglaterra/barclays-premier-league/chelsea/tottenham/3029335").get();

        Elements stats = doc.getElementsByClass("results competition-rounds competition-half-padding").select("tr");

        for (int i = 1; i < stats.size(); i++) {
            classifiacao = stats.get(i).text().split(" ");
            System.out.println(Arrays.toString(classifiacao));

        }
        
        */
       String[] classifiacao;
        
        
        Document doc;
        try {
            doc = Jsoup.connect(url).get();

            
            
            Elements stats = doc.getElementsByClass("results competition-rounds competition-half-padding").select("tr");

            for (int i = 1; i < stats.size(); i++) {
                classifiacao = stats.get(i).text().split(" ");

                if("#".equals(classifiacao[0]))
                    break;
                
                if(classifiacao.length==8){
                
                Object[] inserir = {classifiacao[0],classifiacao[1],classifiacao[2],classifiacao[3],
                classifiacao[4],classifiacao[5],classifiacao[6],classifiacao[7]};
                model.addRow(inserir);
                
                
                }else{
                    Object[] inserir = {classifiacao[0],classifiacao[1]+" "+classifiacao[2],classifiacao[3],classifiacao[4],classifiacao[5],
                classifiacao[6],classifiacao[7],classifiacao[8]};
                model.addRow(inserir);
                
                }     
                    
                
//                System.out.println(Arrays.toString(classifiacao));
//                System.out.println("teste");
            }

            //int qtd = doc.getElementsByClass("component-latest-news--list container").select("li").size();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Sem Tabela");
        }

        
        
    }
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Classificacao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Classificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Time", "P", "J", "V", "E", "D", "Gols"
            }
        ));
        jScrollPane1.setViewportView(Classificacao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Tabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Classificacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
